import Menu from '@/src/components/Menu'
import '@/src/styles/globals.css'
import type { AppProps } from 'next/app'

import { Bai_Jamjuree } from 'next/font/google'
import Head from 'next/head'
export const bai = Bai_Jamjuree({
  weight: ['200', '400'],
  subsets: ['thai'],
  display: 'swap'
})

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Kaew.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <style jsx global>{`
        :root {
          --font-bai: ${bai.style.fontFamily};
        }
      `}</style>

      <Menu />

      <Component {...pageProps} />
    </>
  )
}
