import Container from '@/src/components/Container'
import { animateDownOpacity, animateSlideRightOpacity } from '@/src/utils/animation'
import { motion } from 'framer-motion'
import Head from 'next/head'
import Image from 'next/image'
import hiIcon from 'public/images/hi_icon.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Kaew.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="flex h-screen min-h-screen grid-cols-1 items-center justify-center">
        <div className="font-bai">
          <motion.p
            className="inline-flex text-4xl font-bold text-slate"
            initial={animateDownOpacity.initial}
            animate={animateDownOpacity.animate}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            <span>hi! </span>
            <motion.span
              animate={{ rotate: [0, -10, 0, 10, 0], y: [0, 1, 0, -1, 0] }}
              transition={{ duration: 0.2, repeat: 2, delay: 0.3 }}
            >
              <Image src={hiIcon} width={40} height={40} alt="hi icon" className="ml-2" />
            </motion.span>
          </motion.p>
          <motion.p
            initial={animateSlideRightOpacity.initial}
            animate={animateSlideRightOpacity.animate}
            transition={{ duration: 0.5, delay: 0.15 }}
            className="text-7xl font-bold text-lightest-slate"
          >
            I'm <span className="text-green">Prasit</span>.cpt
          </motion.p>
          <p className="text-slate">current favorite tech stack/tools:</p>
        </div>
      </Container>
      <Container className="flex h-screen min-h-screen grid-cols-1 items-center justify-center">
        <div className="">
          <motion.h1
            className="mb-6 text-center font-bai text-3xl font-bold"
            initial={animateSlideRightOpacity.initial}
            whileInView={animateSlideRightOpacity.animate}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.4 }}
          >
            กำลัง dev อยู่
          </motion.h1>
          <p>คิดไม่ออก</p>
        </div>
      </Container>
    </>
  )
}
